rm -rf build/
rm -rf debian/.debhelper/
rm -rf debian/fcitx-bin/
rm -rf debian/fcitx-data/
rm -rf debian/fcitx-frontend-all/
rm -rf debian/fcitx-frontend-gtk2/
rm -rf debian/fcitx-frontend-gtk3/
rm -rf debian/fcitx-frontend-qt4/
rm -rf debian/fcitx-libs-dev/
rm -rf debian/fcitx-libs/
rm -rf debian/fcitx-module-dbus/
rm -rf debian/fcitx-module-kimpanel/
rm -rf debian/fcitx-module-lua/
rm -rf debian/fcitx-module-x11/
rm -rf debian/fcitx-modules/
rm -rf debian/fcitx-pinyin/
rm -rf debian/fcitx-qw/
rm -rf debian/fcitx-table-all/
rm -rf debian/fcitx-table-bingchan/
rm -rf debian/fcitx-table-cangjie/
rm -rf debian/fcitx-table-dianbaoma/
rm -rf debian/fcitx-table-erbi/
rm -rf debian/fcitx-table-wanfeng/
rm -rf debian/fcitx-table-wbpy/
rm -rf debian/fcitx-table-wubi/
rm -rf debian/fcitx-table-ziranma/
rm -rf debian/fcitx-table/
rm -rf debian/fcitx-tools/
rm -rf debian/fcitx-ui-classic/
rm -rf debian/fcitx/
rm -rf debian/gir1.2-fcitx-1.0/
rm -rf debian/libfcitx-config4/
rm -rf debian/libfcitx-core0/
rm -rf debian/libfcitx-gclient1/
rm -rf debian/libfcitx-qt0/
rm -rf debian/libfcitx-utils0/
rm -rf debian/tmp/
rm -rf obj-x86_64-linux-gnu/
