#!/bin/bash

# 脚本解释器 强制设置为 bash
if [ "$BASH" != "/bin/bash" ] && [ "$BASH" != "/usr/bin/bash" ]; then
    bash "$0" "$@"
    exit $?
fi

# sleep for a little while to avoid duplicate startup

case "${XDG_SESSION_TYPE}" in
    x11)
        sleep 2
        ;;
    wayland)
        bash /bin/fcitx-wayland-start.sh
        ;;
esac

# Test whether fcitx is running correctly with dbus...
fcitx-remote > /dev/null 2>&1

if [ $? = "1" ]; then
    echo "Fcitx seems is not running"
    fcitx
else
    echo "Fcitx is running correctly."
fi
